const ACTION_TYPES = {
  HEROES: {
    LOAD_HEROES: 'LOAD_HEROES',
    ADD_HEROES: 'ADD_HEROES',
    SEARCH_HEROES: 'SEARCH_HEROES',
    RESULT_HEROES: 'RESULT_HEROES'
  }
};

export { ACTION_TYPES };
