const ACTION_TYPES = {
  HEROES: {
    LOAD_HEROES: 'LOAD_HEROES',
    ADD_HEROES: 'ADD_HEROES',
    SEARCH_HEROES: 'SEARCH_HEROES',
    RESULT_HEROES: 'RESULT_HEROES',
    ADD_FAVORITE_HERO: 'ADD_FAVORITE_HERO',
    REMOVE_FAVORITE_HERO: 'REMOVE_FAVORITE_HERO',
    LOAD_HEROES_ERROR: 'LOAD_HEROES_ERROR'
  },
  PAGES: {
    INCREMENT_PAGE: 'INCREMENT_PAGE',
    DECREMENT_PAGE: 'DECREMENT_PAGE'
  }
};

export { ACTION_TYPES };
